<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.12" />
    <PackageReference Include="MudBlazor" Version="9.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CromoBound.Contracts\CromoBound.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CromoBound.Client.Tests" />
  </ItemGroup>

</Project>
